In [1]:
import pandas as pd

In [2]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
pd.read_json('https://v6.exchangerate-api.com/v6/19dce3a9b1b66ebc28681b17/latest/USD')

,result,documentation,terms_of_use,time_last_update_unix,time_last_update_utc,time_next_update_unix,time_next_update_utc,base_code,conversion_rates
USD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,1.0000
AED,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,3.6725
AFN,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,62.5225
ALL,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,82.4733
AMD,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,377.6966
...,...,...,...,...,...,...,...,...,...
YER,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,236.4341
ZAR,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,16.8255
ZMW,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,19.5692
ZWG,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,25.3025
ZWL,success,https://www.exchangerate-api.com/docs,https://www.exchangerate-api.com/terms,1774310401,"Tue, 24 Mar 2026 00:00:01 +0000",1774396801,"Wed, 25 Mar 2026 00:00:01 +0000",USD,25.3025

In [4]:
!pip install mysql.connector

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [6]:
import mysql.connector

ModuleNotFoundError: No module named 'mysql'