In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df = pd.read_csv('cars.csv')
df.sample(5)

           brand  km_driven    fuel         owner  selling_price
4211      Maruti      50000  Diesel   First Owner         650000
5370  Volkswagen     100000  Diesel  Second Owner         370000
154      Hyundai      95000  Petrol   First Owner         550000
7702      Jaguar      45000  Diesel   First Owner        3200000
4933      Maruti     100000     CNG  Second Owner          80000

### 1) one hot encoding using pandas

In [3]:
df['brand'].nunique()

32

In [4]:
pd.get_dummies(df,columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

### 2) k-1 encoing

In [5]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

### 3) one hot encoding using scikit learn

In [6]:
from sklearn.model_selection import train_test_split
X_train , x_test , y_train , y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size = 0.3 , random_state=0)

In [7]:
X_train.head()

          brand  km_driven    fuel        owner
5224       Tata      20000  Petrol  First Owner
520      Maruti      30000  Petrol  First Owner
36       Maruti      15000  Petrol  First Owner
5782       Ford      53000  Diesel  First Owner
6522  Chevrolet     120000  Diesel  First Owner

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(drop='first')

In [35]:
x_train_new =ohe.fit_transform(X_train[['fuel', 'owner']]).toarray()

In [36]:
x_test_new = ohe.transform(x_test[['fuel', 'owner']]).toarray

In [37]:
np.hstack((X_train[['brand', 'km_driven']].values, x_train_new)).shape

(5689, 9)

### 4) one hot encoding with the top catergories

In [39]:
counts = df['brand'].value_counts()
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [40]:
df['brand'].nunique()
treshold = 50

In [41]:
repl = counts[counts<= treshold ].index

In [43]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Datsun,Ford,Honda,Hyundai,Jaguar,Mahindra,Maruti,Mercedes-Benz,Nissan,Renault,Skoda,Tata,Toyota,Volkswagen,Volvo,uncommon
0,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8124,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
8127,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False