In [1]:
import pandas as pd
import numpy as np
import matplotlib as mlt
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv('train.csv', usecols=['Age', 'Pclass', 'Fare', 'Survived'])
df.sample(5)

     Survived  Pclass   Age     Fare
76          0       3   NaN   7.8958
745         0       1  70.0  71.0000
726         1       2  30.0  21.0000
888         0       3   NaN  23.4500
566         0       3  19.0   7.8958

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Age       714 non-null    float64
 3   Fare      891 non-null    float64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [5]:
df.describe()

         Survived      Pclass         Age        Fare
count  891.000000  891.000000  714.000000  891.000000
mean     0.383838    2.308642   29.699118   32.204208
std      0.486592    0.836071   14.526497   49.693429
min      0.000000    1.000000    0.420000    0.000000
25%      0.000000    2.000000   20.125000    7.910400
50%      0.000000    3.000000   28.000000   14.454200
75%      1.000000    3.000000   38.000000   31.000000
max      1.000000    3.000000   80.000000  512.329200

In [6]:
df.isnull().mean()*100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [7]:
x = df.drop(columns=['Survived'])
y = df['Survived']

In [8]:
x_train , x_test , y_train , Y_test = train_test_split(x, y, random_state=4, test_size=0.3)

In [9]:
x_train.head()

     Pclass   Age     Fare
537       1  30.0  106.425
401       3  26.0    8.050
554       3  22.0    7.775
213       2  30.0   13.000
434       1  50.0   55.900

In [36]:
knn = KNNImputer(n_neighbors=10, weights='distance')
x_train_knn = knn.fit_transform(x_train)
X_test__knn = knn.transform(x_test)

In [37]:
pd.DataFrame(x_train_knn, columns=x_train.columns)

     Pclass   Age      Fare
0       1.0  30.0  106.4250
1       3.0  26.0    8.0500
2       3.0  22.0    7.7750
3       2.0  30.0   13.0000
4       1.0  50.0   55.9000
..      ...   ...       ...
618     3.0  40.0   27.9000
619     3.0  29.0   15.2458
620     2.0  31.0   10.5000
621     1.0  56.0   30.6958
622     2.0  32.5   30.0708

[623 rows x 3 columns]

In [38]:
lr = LogisticRegression()
lr.fit(x_train_knn, y_train)
y_pred = lr.predict(X_test__knn)

In [39]:
accuracy_score(Y_test, y_pred)

0.7238805970149254