In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import KBinsDiscretizer
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('train.csv')[['Age', 'Fare', 'SibSp', 'Parch', 'Survived']]

In [3]:
df.dropna(inplace=True)

In [4]:
df.sample(10)

      Age     Fare  SibSp  Parch  Survived
678  43.0  46.9000      1      6         0
259  50.0  26.0000      0      1         1
249  54.0  26.0000      1      0         0
310  24.0  83.1583      0      0         1
553  22.0   7.2250      0      0         1
221  27.0  13.0000      0      0         0
720   6.0  33.0000      0      1         1
204  18.0   8.0500      0      0         1
503  37.0   9.5875      0      0         0
442  25.0   7.7750      1      0         0

In [5]:
df['family'] = df['SibSp']+ df['Parch']

In [6]:
df.sample(10)

      Age      Fare  SibSp  Parch  Survived  family
50    7.0   39.6875      4      1         0       5
183   1.0   39.0000      2      1         1       3
307  17.0  108.9000      1      0         1       1
35   42.0   52.0000      1      0         0       1
683  14.0   46.9000      5      2         0       7
276  45.0    7.7500      0      0         0       0
10    4.0   16.7000      1      1         1       2
577  39.0   55.9000      1      0         1       1
13   39.0   31.2750      1      5         0       6
434  50.0   55.9000      1      0         0       1

In [7]:
df.drop(columns=['SibSp', 'Parch'], inplace=True)

In [8]:
df.sample(10)

      Age     Fare  Survived  family
686  14.0  39.6875         0       5
610  39.0  31.2750         0       6
807  18.0   7.7750         0       0
756  28.0   7.7958         0       0
191  19.0  13.0000         0       0
251  29.0  10.4625         0       2
165   9.0  20.5250         1       2
149  42.0  13.0000         0       0
163  17.0   8.6625         0       0
98   34.0  23.0000         1       1

In [9]:
x = df.drop(columns='Survived')
y = df['Survived']

In [10]:
x_train, x_test , y_train , y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [11]:
x_train.sample(10)

      Age      Fare  family
717  27.0   10.5000       0
609  40.0  153.4625       0
874  28.0   24.0000       1
764  16.0    7.7750       0
326  61.0    6.2375       0
211  35.0   21.0000       0
683  14.0   46.9000       7
44   19.0    7.8792       0
867  31.0   50.4958       0
482  50.0    8.0500       0

In [12]:
#without binarization

clf = DecisionTreeClassifier()
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)
accuracy_score(y_test, y_pred)

0.6511627906976745

In [14]:
np.mean(cross_val_score(DecisionTreeClassifier(), x, y , cv=10, scoring='accuracy'))

np.float64(0.6443075117370892)

In [15]:
# Appylung binarization

from sklearn.preprocessing import Binarizer

In [16]:
trf = ColumnTransformer([
    ('bin', Binarizer(copy=False), ['family'])
], remainder='passthrough')

In [17]:
x_train_trf = trf.fit_transform(x_train)
x_test_trf = trf.transform(x_test)

In [18]:
pd.DataFrame(x_train_trf, columns=['family', 'Age', 'Fare'])

     family   Age      Fare
0       0.0  21.0    8.0500
1       1.0   5.0   27.7500
2       0.0  28.5    7.2292
3       0.0  59.0    7.2500
4       0.0  40.0   31.0000
..      ...   ...       ...
494     1.0  46.0   61.1750
495     0.0  25.0   13.0000
496     0.0  41.0  134.5000
497     1.0  33.0   20.5250
498     0.0  33.0    7.8958

[499 rows x 3 columns]

In [19]:
clf = DecisionTreeClassifier()
clf.fit(x_train_trf, y_train)
y_pred2 = clf.predict(x_test_trf)
accuracy_score(y_test, y_pred2)

0.627906976744186